services:
  postgis:
    image: postgis/postgis
    container_name: energimerke-db
    restart: always
    environment:
      - POSTGRES_DB=Energimerking
      - POSTGRES_USER=Kodehode
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432
    volumes:
      - postgis:/var/lib/postgresql/data
      - db-init:/docker-entrypoint-initdb.d
      - ./Data:/import
  
      
  pgadmin:
    image: dpage/pgadmin4:9.8 # Use the official pgAdmin image
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: securepassword
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgis
volumes:
  postgis:
  pgadmin_data:
  db-init:
  