// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ms_efcore_sample.models;

#nullable disable

namespace ms_efcore_sample.Migrations.CoordinateDb
{
    [DbContext(typeof(CoordinateDbContext))]
    [Migration("20260429122120_EnergiMerke")]
    partial class EnergiMerke
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ms_efcore_sample.models.Coordinate", b =>
                {
                    b.Property<int>("CoordinateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CoordinateId"));

                    b.Property<int>("EPSG")
                        .HasColumnType("integer");

                    b.Property<Point>("GeographyPoint")
                        .IsRequired()
                        .HasColumnType("geography(Point, 4258)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("CoordinateId");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("ms_efcore_sample.models.CoordinateNoPoint", b =>
                {
                    b.Property<int>("CoordinateNoPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CoordinateNoPointId"));

                    b.Property<int>("EPSG")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("CoordinateNoPointId");

                    b.ToTable("CoordinateNoPoints");
                });

            modelBuilder.Entity("ms_efcore_sample.models.Eiendom", b =>
                {
                    b.Property<int>("EiendomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EiendomId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ByggType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CoordinateId")
                        .HasColumnType("integer");

                    b.Property<int>("KommuneId")
                        .HasColumnType("integer");

                    b.HasKey("EiendomId");

                    b.HasIndex("CoordinateId");

                    b.HasIndex("KommuneId");

                    b.ToTable("Eiendommer");
                });

            modelBuilder.Entity("ms_efcore_sample.models.EnergiMerke", b =>
                {
                    b.Property<int>("EnergiMerkeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnergiMerkeId"));

                    b.Property<int?>("EiendomId")
                        .HasColumnType("integer");

                    b.Property<int>("VurderingsGrad")
                        .HasColumnType("integer");

                    b.HasKey("EnergiMerkeId");

                    b.HasIndex("EiendomId");

                    b.ToTable("EnergiMerke");
                });

            modelBuilder.Entity("ms_efcore_sample.models.Kommune", b =>
                {
                    b.Property<int>("KommuneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KommuneId"));

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KommuneId");

                    b.ToTable("Kommuner");
                });

            modelBuilder.Entity("ms_efcore_sample.models.Eiendom", b =>
                {
                    b.HasOne("ms_efcore_sample.models.Coordinate", "Coordinate")
                        .WithMany()
                        .HasForeignKey("CoordinateId");

                    b.HasOne("ms_efcore_sample.models.Kommune", "Kommune")
                        .WithMany()
                        .HasForeignKey("KommuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordinate");

                    b.Navigation("Kommune");
                });

            modelBuilder.Entity("ms_efcore_sample.models.EnergiMerke", b =>
                {
                    b.HasOne("ms_efcore_sample.models.Eiendom", null)
                        .WithMany("EnergiMerker")
                        .HasForeignKey("EiendomId");
                });

            modelBuilder.Entity("ms_efcore_sample.models.Eiendom", b =>
                {
                    b.Navigation("EnergiMerker");
                });
#pragma warning restore 612, 618
        }
    }
}
